apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: airmiles2
  name: airmiles2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airmiles2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: airmiles2
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: etansoclof/airmiles:1.01
          imagePullPolicy: ""
          name: airmiles2
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "200m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}