apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    app: nor
  name: nor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        app: nor
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: etansoclof/airmiles:1.01
          imagePullPolicy: ""
          name: nor
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "200m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    app: mal
  name: mal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mal
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        app: mal
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: etansoclof/airmiles:1.01
          imagePullPolicy: ""
          name: mal
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "200m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tk
spec:
  selector:
    app: tk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tk
  namespace: default
  labels:
    app: tk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tk
  template:
    metadata:
      labels:
        app: tk
    spec:
      containers:
        - name: tk
          image: 'etansoclof/tk:1.03'
          command:
            - sh
            - '-c'
            - echo Container 1 is Running ; sleep 3600
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always