apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    io.kompose.service: rabbit
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbit
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit
    spec:
      containers:
        - image: rabbitmq:3-management
          imagePullPolicy: ""
          name: rabbit
          ports:
            - containerPort: 5672
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: k8s.gcr.io/redis:e2e  # or just image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
          image: etansoclof/gateway:1.01
          imagePullPolicy: ""
          name: gateway
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: bookings
  name: bookings
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookings
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
        prometheus.io/scrape: "true"      # must be quoted
        prometheus.io/port: "8000" # must be quoted
        prometheus.io/path: "/"
      creationTimestamp: null
      labels:
        io.kompose.service: bookings
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: etansoclof/bookings:metric4
          imagePullPolicy: ""
          name: bookings
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: airmiles
  name: airmiles
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airmiles
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: airmiles
    spec:
      containers:
        - env:
            - name: RABBIT_HOST
              value: rabbit
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: guest
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          image: etansoclof/airmiles:1.01
          imagePullPolicy: ""
          name: airmiles
          resources:
            requests:
              cpu: "10m"
            limits:
              cpu: "200m"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
